# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8802d89f87bef447847b29a4795523f5839fae80f4f0d2400164a0fefac986baec23a0a7cee92796fe1d421d650c3b146ef82439c38241cfb1e9dd330daf6942

test:
  secret_key_base: 7352dfeea4ac42568b1f7530019026c44eef56d1aa01b10c764652e085967a13121f4f449fbaf428c9da9ea6f9a1daaf2627eecd66a8013356e944f3dc84e1c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
